spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: 123456

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    cn.zhxu.bs: DEBUG